# pipeline_pipeline_executor.py (Executor Role)
# This module defines the Executor class responsible for executing plans and generating code changes.

from .intelligence_code_executor import get_executor_response  # Function to generate executor responses using LLM

class Executor:
    """
    The Executor class handles the execution phase of the agent's pipeline.
    It takes a plan and relevant context to generate proposed code changes.
    """

    def __init__(self, main_goal: str):
        """
        Initializes the Executor with the current goal.

        Args:
            main_goal (str): The programming goal to achieve
        """
        self.main_goal = main_goal
        self.working_dir = None  # Working directory for generating relative code changes

    def set_working_directory(self, path: str):
        """
        Sets the working directory for generating code changes relative to this path.

        Args:
            path (str): The candidate directory path
        """
        self.working_dir = path

    def execute_plan(self, plan: str, backpack: list[dict]) -> str:
        """
        Executes the given plan by calling the LLM executor with all parameters.
        Generates code changes relative to self.working_dir.

        Args:
            plan (str): The structured plan in JSON format
            backpack (list[dict]): List of relevant files with context

        Returns:
            str: The proposed code change generated by the LLM
        """
        return get_executor_response(self.main_goal, None, backpack, plan, self.working_dir)